package Interfaces;

import Clases.BD;
import Clases.ManejoDatos;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class verBDPanel extends javax.swing.JPanel {

    ManejoDatos md = new ManejoDatos();
    ArrayList<BD> bds;
    static int bdIndex;

    public verBDPanel() {
        this.bds = new ArrayList<BD>();
        initComponents();

        try {
            bds = md.leerDatosBD2();
            //ArrayList<BD> prueba = (ArrayList<BD>) bds;
            for (int i = 0; i < bds.size(); i++) {
                comboBoxBDS.addItem((bds.get(i)).getNombre());
            }

            System.out.println(bds.get(0));
            System.out.println(bds);
            System.out.println(bds.get(0).getClass());

        } catch (IOException ex) {
            Logger.getLogger(verBDPanel.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error en metodo \"LeerDatosBd\" en verDBPanel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(verBDPanel.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error en Metodo leerDatosBD2 en verBDPanel");
        }
        //System.out.println(bds.get(bdIndex).getNombre());

        //listaBD = new JList(bds.toArray());
//        String[] lBD = (String[]) bds.toArray();
//        for(BD bd : bds){
//            System.out.println(bd.getNombre());
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSeleccionarBD = new javax.swing.JButton();
        BDPanel = new javax.swing.JPanel();
        comboBoxBDS = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(503, 364));

        jLabel1.setText("Bases de Datos");

        btnSeleccionarBD.setText("Seleccionar");
        btnSeleccionarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarBDActionPerformed(evt);
            }
        });

        comboBoxBDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxBDSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BDPanelLayout = new javax.swing.GroupLayout(BDPanel);
        BDPanel.setLayout(BDPanelLayout);
        BDPanelLayout.setHorizontalGroup(
            BDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BDPanelLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(comboBoxBDS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        BDPanelLayout.setVerticalGroup(
            BDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BDPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(comboBoxBDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeleccionarBD)
                    .addComponent(jLabel1))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BDPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(btnSeleccionarBD)
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(25, Short.MAX_VALUE)
                    .addComponent(BDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarBDActionPerformed
        ActionListener action = new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                bdIndex = comboBoxBDS.getSelectedIndex();
//                System.out.println(bdIndex);

            }
        };
        comboBoxBDS.addActionListener(action);
        System.out.println(bdIndex);
    }//GEN-LAST:event_btnSeleccionarBDActionPerformed

    private void comboBoxBDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxBDSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxBDSActionPerformed

    static int indexBD() {
        int index = 0;
        index = bdIndex;

        return index;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BDPanel;
    private javax.swing.JButton btnSeleccionarBD;
    private javax.swing.JComboBox<String> comboBoxBDS;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
